### ISSUE TITLE
power apps can't be imported

### ISSUE THREAD

**Issue by ajy401** [loryanstrant/BookingsWithMeSignatureManager#1]
Thanks heaps Loryan. However, I can't import the power apps package - can you please advise?
something went wrong, please try again is the error I get.

**Comment by loryanstrant** [comment]
Can you please provide an image of the screen where you're getting the error?
Are you trying to import it as a Power App package, or a Power Platform solution?

**Comment by ajy401** [comment]
Attached is the error screenshot Loryan. 
I tried to import it as a power app package
<img width="617" alt="powerapps error" src="https://github.com/user-attachments/assets/aa3ff3a7-51b7-4b3c-adab-0a32a1231fd7">

**Comment by loryanstrant** [comment]
Got it, thanks.
The file is actually a Power Platform solution file.
So if you head to the Solutions section of Power Automate or Power Apps, you should be able to import it.
